### ISSUE TITLE
Running Model on Google Dev Board

### ISSUE THREAD

**Issue by mmmoakley** [googlecreativelab/teachablemachine-community#130]
I exported a tensorflow lite model for the edgetpu
When running it i get this error
using this syntax
edgetpu_detect_server --model model_edgetpu.tflite --labels labels.txt

Traceback (most recent call last):
  File "/usr/bin/edgetpu_detect_server", line 11, in <module>
    load_entry_point('edgetpuvision==1.0', 'console_scripts', 'edgetpu_detect_server')()
  File "/usr/lib/python3/dist-packages/edgetpuvision/detect_server.py", line 33, in main
    run_server(add_render_gen_args, render_gen)
  File "/usr/lib/python3/dist-packages/edgetpuvision/apps.py", line 43, in run_server
    camera = make_camera(args.source, next(gen), args.loop)
  File "/usr/lib/python3/dist-packages/edgetpuvision/detect.py", line 144, in render_gen
    engines, titles = utils.make_engines(args.model, DetectionEngine)
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 53, in make_engines
    engine = engine_class(model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/detection/engine.py", line 85, in __init__
    'This model has {}.'.format(output_tensors_sizes.size)))
ValueError: Dectection model should have 4 output tensors!This model has 1.

**Comment by GautamBose** [comment]
Hey, 

The edgetpu_detect_server program is designed to demo some specific models that coral provides. 

To use the models that come out of teachable machine, check out the snippet in the export panel for Coral. You can also find that snippet here: 

https://github.com/googlecreativelab/teachablemachine-community/blob/master/snippets/markdown/image/edgetpu/python.md
