### ISSUE TITLE
[BUG]: Python code for TensorFlow not working

### ISSUE THREAD

**Issue by divneetskapoor** [googlecreativelab/teachablemachine-community#192]
**Describe the bug**
Upon downloading the keras model (.h5), and executing the Python script, following error appears:

Traceback (most recent call last):
  File "D:/New AI/tm_test.py", line 9, in <module>
    model = tensorflow.keras.models.load_model('keras_model.h5')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 234, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 324, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 74, in deserialize
    printable_module_name='layer')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 349, in from_config
    custom_objects=custom_objects)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 74, in deserialize
    printable_module_name='layer')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 402, in from_config
    return cls(**config)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\input_layer.py", line 69, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.7.0
 - TensorFlow 1.15.0

**Comment by Gopu2001** [comment]
Did you try updating Tensorflow? There are a bunch of differences between TensorFlow 1 and TensorFlow 2
