### ISSUE TITLE
Keras: unrecognized keyword arguments

### ISSUE THREAD

**Issue by zxsq-cc** [googlecreativelab/teachablemachine-community#49]
When running the example code from the keras section, the following error occurs:
```
Traceback (most recent call last):
  File "/home/pi/Documents/converted_keras/TMexample.py", line 7, in <module>
    model = tensorflow.keras.models.load_model('/home/pi/Documents/converted_keras/keras_model.h5')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 137, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 162, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 97, in deserialize
    printable_module_name='layer')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 358, in from_config
    custom_objects=custom_objects)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 97, in deserialize
    printable_module_name='layer')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 358, in from_config
    custom_objects=custom_objects)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 97, in deserialize
    printable_module_name='layer')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1130, in from_config
    process_layer(layer_data)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1114, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 97, in deserialize
    printable_module_name='layer')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 193, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 456, in from_config
    return cls(**config)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 81, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))
```

Any guidance on how to get the model running?

**Comment by GautamBose** [comment]
Make sure you are running on a version of tensorflow > 1.15.0. You can upgrade the version by running 

> pip3 install --upgrade tensorflow

**Comment by zxsq-cc** [comment]
rats... tensorflow 1.15 seems not to be available for arm (RasPi) yet.

**Comment by zxsq-cc** [comment]
Alright, I got tensorflow 2.0.0 installed now. 
Running with the boilerplate from the export menu gives me the errors:
```WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
```
and
```file "tffull.py", line 11, in <module>
  data[0] = normalized_image_array
ValueError: could not broadcast input array from shape (1900,1900,3) into shape (224,224,3)
```

**Comment by HalfdanJ** [comment]
I think was just solved in this pr: https://github.com/googlecreativelab/teachablemachine-community/pull/53 Small tweak to the code snippet

**Comment by zxsq-cc** [comment]
I also missed an `image = ` before `image.resize', running now to see if that fixed it.
